
/**
* receiver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from receptor.idl
* Friday, August 24, 2018 3:01:33 PM BRT
*/

public interface receiver extends receiverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface receiver
